### PR TITLE
Use logging

### PR DESCRIPTION
**Pull request by ytterbium**
I removed the msg function to use logging module.
The main logical change is a personnal Formatter to display color. Except this, it is mainly code translation.

The code must have exactly the same comportment.

Now, some improvements can be made.
- change information level. Most of messages can be considered as debug information, and should be shown with verbosity=high. Verbosity=none should shown only warnings and higher
- auto color based on log level : all warnings may be red, all infos white and the remaining without color. So we could remove the color reference in the log functions and the color will be put automatically.
- change Formatter for log file. Since there is no color in log files, we could change the formatter to change the log level in log files.

### CODE REVIEW

**Comment by suizokukan** [comment]
Thank you very much for this great pull request ! Since your code breaks some stuff, I have to take some times before accepting your P.R. I'm very impressed by the trick used by the `_log(self, *args, **kwargs)` method . I like very much the way you removed the msg() function.

Some remarks : 
- `CST_V_LINUXCONSOLECOLORS` is now useless;
- I would like to add the missing config keys (in katal.ini) you added in the TODOs before accepting the P.R.; something like `"[log file]use color : if possible|never"` and `"[log file] backup count : 0|1|2|3|..."`
- it would be nice not to add the color argument by calling `logging.info()|warning()|...` I'm not sure how to do this : is it possible to specify a color by level ?
- I don't understand the `"TODO replace {:15}"` line. Can you be more specific ?

**Comment by ytterbium** [comment]
- For the config file, I can do that now, but I'm modifying the config parsing. I would like to have default config keys, so that we don't have to specify some keys not very useful (such as backup count). Moreover, it would let to have priority : command line will be considered first, then my_folder/.katal/katal.ini , then ~/.katal/katal.ini and finally default values. (I have a question : are return code when there are errors are very useful ? We could raise exception and then catch them to detect errors, it would be more pythonic)
- In the ColorFormater, we can do conditional color formating. For example if level <= DEBUG, no color will be automatically set, if DEBUG< level <= INFO, white will be set, and if LEVEL >= WARNING, automatically it will be red. So when a warning message is raised, the `color='red'` argument will not be needed
- `"TODO replace {:15}"` : I only forgot to remove this, it aimed to remember me to see if `%15s` was strictly equivalent to `{:15}`

**Comment by ytterbium** [comment]
There is a problem to add missing config keys: the loggers are defined before config file is parsed. 
It leads to a bug: the logs are never written in log file, since by default USE_LOGFILE is False, and the key from config file is never used.

To solve the issue, I see several workaround, from the simpliest to the most complex:
- define loggers after config file parsing. It would let to have from the start the correct config values, including `use color`. The problem is that there can't be any logging during the parsing, and if there is an error, only raw tracebacks can be printed
- define StreamHandler, parse the config file, and if required, define the FileHandler. So logging to the console can be made during the parser. But first, the logging during the parsing won't appear in the log file, and there is the problem of color. Does the stream should be colored before reading config file ?
- define a StreamHandler and use a MemoryHandler as a buffer. After the parsing, the content of the MemoryHandler will be written in the log file. It is about the same as above, but it let to keep tracks of all the logs.

Which way do you prefer ?

**Comment by suizokukan** [comment]
The first idea, definitively, since it's the only one I understand. :smile:  
More seriously, since the line...
`CFG_PARAMETERS = read_parameters_from_cfgfile(configfile_name)`
... is called at the very beginning of `main_warmup()`, I don't really care about not logging the messages occuring while parsing the log files. Is it so important to keep track of **all** the logs ? Please feel free to disagree with me !

**Comment by ytterbium** [comment]
(en français ce sera plus facile)

Actuellement, en appelant main_logger() au tout début de main, on logue tout, mais on prend pas en compte la valeur de 'use log file' dans le fichier de conf.
- la première solution, déplacer l'appel à main_logger après le parsing du fichier de conf implique qu'on ne peut rien loguer avant, et remonter tous les problèmes de fichiers non trouvés/mal formés. Les tracebacks s'afficheront brutes.
- la deuxième solution résout en grande partie le problème en définissant comme actuellement un logger avec un StreamHandler au tout début, comme ça tous les messages avant et pendant le parsing du fichier de conf s'afficheront dans la console, puis selon la valeur de la conf, on définit ou non un FileHandler qui recopiera  par la suite tous les messages suivants dans le fichier de log. Le petit problème est que le fichier de log ne contiendra pas tous les messages, il manquera les tous premiers.
- pour combler ce manque, c'est la troisième solution. On stocke les messages durant le parsing en mémoire, puis on les recopie après dans le fichier de log, s'il existe. C'est juste pour permettre une recopie totale entre l'affichage dans la console et le fichier de log, mais ce n'est effectivement pas critique (sauf en cas d'utilisation en arrière-plan pour vérifier que les fichiers de configuration sont bien situés ?)

Si on ne se préoccupe pas d'afficher tous les messages de log dans le fichier, la meilleure solution serai pour moi la deuxième

**Comment by suizokukan** [comment]
Oh pardon, j'avais en fait bien compris ce que tu disais... Je voulais faire  de l'humour car les deux dernières solutions me paraissaient trop complexes par rapport aux ambitions de Katal. Promis, c'est la dernière fois que j'ironise sur GitHub, désolé pour la perte de temps :disappointed: 
Donc je penche plutôt pour la première solution car je ne pense pas qu'il soit important de garder la trace de **tous** les messages, d'autant plus que la ligne 
`CFG_PARAMETERS = read_parameters_from_cfgfile(configfile_name)`
est appelée très en amont du programme, au tout début de main_warmup().

Comme je te le disais :  

> Is it so important to keep track of all the logs ? Please feel free to disagree with me !

**Comment by ytterbium** [comment]
Voilà, ça devrait être bon maintenant. 
Vu qu'on définit les loggers après avoir parser les fichiers de conf, j'ai enlevé tous les logs pendant le parsage et j'ai mis des prints dans les exceptions.

**Comment by suizokukan** [comment]
Thank you for the P.R. I removed the `color="xxx"` argument in every call to`LOGGER.info|warning|`... since the color is defined by the log level.

**Pull request merged**
